version: '3'
services:
  # node:
  #   build:
  #     context: ./node-project 
  #   ports:
  #     - "5000:5000"
  # frontend:
  #   build:
  #     context: ./react-project
  #   ports:
  #     - "3000:3000"
  spring2:
    #image: openjdk:11
    build:  ./spring-project3
    
    ports:
      - "9090:8080"
    volumes:
      - ./spring-project3:/app
      #- ./spring-project3/build:/app/build
    working_dir: /app
    command: sh -c './gradlew build && java -jar /app/build/libs/springDocker.jar'